# dir_config.py
#
# This module prepares the local filesystem directory structure
# required by the SoniEffect backend at runtime.
#
# These directories are specifically designed for the
# SoniEffect video-to-audio conversion pipeline.
#
# SoniEffect allows users to extract audio from video files.
# During this process:
# - Input video files are stored temporarily
# - Output audio files are generated temporarily
# - No files in these directories are considered permanent
#
# All files created inside these directories are TEMPORARY.
# Lifecycle management and deletion is handled by:
# lib/services/data_cleaner.py
#
# This file ONLY ensures directories exist.
# It does NOT perform cleanup.
# It does NOT manage file lifetimes.
#
# The design goals of this file are:
# - Absolute simplicity
# - Maximum runtime safety
# - Zero external dependencies
# - Predictable behavior in production environments
#
# This file performs exactly one responsibility:
# ensuring required data directories exist before use.
#
# Nothing is deleted.
# Nothing is overwritten.
# Nothing is modified if already present.
#
# This file is safe to import:
# - Multiple times
# - From any module
# - At any stage of application execution
#
# Missing directories are a common source of:
# - Conversion failures
# - File write errors
# - Production crashes
#
# This file eliminates that entire class of failures.

from pathlib import Path

# DATA_DIR is the root directory used for all temporary
# filesystem-based data generated by SoniEffect.
#
# Every video or audio file involved in the conversion
# process lives under this directory.
#
# This directory does NOT store user data permanently.
# It only exists to support short-lived processing tasks.
#
# The path is intentionally relative to the project root
# to keep deployments portable across environments.
#
# pathlib.Path is used to ensure:
# - Cross-platform compatibility
# - Safe path joining
# - Clear filesystem semantics
DATA_DIR: Path = Path("lib/data")

# AUDIO_DIR is a subdirectory inside DATA_DIR used ONLY
# for temporary audio files produced during conversion.
#
# Conversion flow:
# - A video is processed
# - Audio is extracted
# - The resulting audio file is written here
#
# Files in this directory are:
# - Temporary
# - Not user-owned
# - Safe to delete after processing
#
# Cleanup is handled centrally by:
# lib/services/data_cleaner.py
#
# Keeping audio output isolated:
# - Prevents mixing with video inputs
# - Simplifies cleanup logic
# - Reduces risk of deleting wrong files
AUDIO_DIR: Path = DATA_DIR / "audio"

# VIDEO_DIR is a subdirectory inside DATA_DIR used ONLY
# for temporary input video files.
#
# Conversion flow:
# - User provides or uploads a video
# - Video is stored temporarily in this directory
# - Video is read by the conversion pipeline
#
# Files in this directory are:
# - Temporary
# - Short-lived
# - Automatically cleaned up
#
# No long-term data should ever be stored here.
#
# Separation of input (video) and output (audio):
# - Improves safety
# - Improves clarity
# - Prevents accidental overwrites
VIDEO_DIR: Path = DATA_DIR / "video"

# This function guarantees that a directory exists on disk.
#
# If the directory does not exist:
# - It is created automatically
#
# If the directory already exists:
# - Nothing happens
#
# This makes the function idempotent and safe to call
# repeatedly without side effects.
#
# Parent directories are created automatically when needed.
def ensure_directory_exists(directory: Path) -> None:
    # parents=True allows nested directory creation
    # exist_ok=True prevents errors if the directory already exists
    # This call is safe under normal filesystem conditions
    directory.mkdir(parents=True, exist_ok=True)

# Directory initialization occurs immediately on import.
#
# This guarantees that when the conversion pipeline runs:
# - Input video directory exists
# - Output audio directory exists
#
# No additional directory checks are required elsewhere
# in the codebase, reducing duplication and bugs.
ensure_directory_exists(DATA_DIR)
ensure_directory_exists(AUDIO_DIR)
ensure_directory_exists(VIDEO_DIR)

# End of dir_config.py
